name: otti_calendar
description: "A Calendar."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  table_calendar: ^3.1.1
  intl: ^0.19.0
  lunar: ^1.3.3
  http: ^1.1.0
  icalendar_parser: ^1.1.1
  image_picker: ^1.1.2
  flutter_overlay_window: ^0.4.3
  permission_handler: ^11.3.1
  fl_chart: ^0.69.0
  
  # Audio and Network
  record: ^6.1.2 # Upgraded to fix the build error
  dio: ^5.4.3+1
  path_provider: ^2.1.3
  crypto: ^3.0.3
  
  # Auth and Storage
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
